
if ~exist('loc');
    loc='mypc';
    % loc='cluster';
end

global loc
if strcmp(loc,'mypc');
    expdir='Y:/claire/speaker-listener/';
else
   
    expdir='/scratch/claire/speaker-listener/';
    addpath(genpath([expdir '/../tools/isc_nifti_kit_080916']));
end

addpath([expdir '/scripts_speaker-listener/' ]);
experiments={'pieman','bronx','merlin','sherlock'};
tr=[1.5 1.5 1.5 1.5];

volsize=[65 77 49];
voxn=prod(volsize);

listeners={...
    'listener01',...
    'listener02',...
    'listener03',...
    'listener04',...
    'listener05',...
    'listener06',...
    'listener07',...
    'listener08',...
    'listener09',...
    'listener10',...
    'listener11',...
    'listener12',...
    'listener13',...
    'listener14',...
    'listener15',...
    'listener16',...
    'listener17',...
    'listener18'...
    };